### ISSUE TITLE
spawning canary presumes installed at /Applications but I have it in ~/Applications (macOS)

### ISSUE THREAD

**Issue by efx** [krisselden/chrome-debugging-client#7]
stumbled across this and your gist (https://gist.githubusercontent.com/krisselden/2487706bcbf37da26d4a89d0f74df768/raw/445e0ef44f2f751ec0116e8f21ed86bff1962da8/index.js). Thanks, looks like a better way to determine code coverage.
I quick-and-dirty bundled that gist to run with node 8.2.1, but got this error:
```
node bundle.js       
{ Error: spawn /Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary ENOENT
    at exports._errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn /Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary',
  path: '/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary',
  spawnargs: 
   [ '--disable-breakpad',
     '--noerrdialogs',
     '--allow-insecure-localhost',
     '--disable-hang-monitor',
     '--disable-notifications',
     '--disable-web-security',
     '--disable-v8-idle-tasks',
     '--disable-xss-auditor',
     '--ignore-certificate-errors',
     '--no-sandbox',
     '--reduce-security-for-testing',
     '--safebrowsing-disable-auto-update',
     '--v8-cache-options=none',
     '--process-per-tab',
     '--use-mock-keychain',
     '--password-store=basic',
     '--remote-debugging-port=0',
     '--disable-add-to-shelf',
     '--disable-background-networking',
     '--disable-client-side-phishing-detection',
     '--disable-component-extensions-with-background-pages',
     '--disable-component-update',
     '--disable-default-apps',
     '--disable-domain-reliability',
     '--disable-extensions',
     '--disable-features=NetworkPrediction',
     '--disable-popup-blocking',
     '--disable-prompt-on-repost',
     '--disable-sync',
     '--disable-translate',
     '--metrics-recording-only',
     '--no-default-browser-check',
     '--no-experiments',
     '--no-first-run',
     '--no-ping',
     '--no-proxy-server',
     '--user-data-dir=/var/folders/r6/1tb0c_rn22xdhm39d62y6rfh0000gn/T/tmpdxD75q',
     '--window-size=414,736',
     'about:blank' ] }
```
Error seems self-explanatory, but I couldn't find where this project actually invokes `spawnBrowser`. 
# expectation
I would expect to be able to configure the path to the Canary executable, or have it automatically fall back to `~/Applications`.
# versions
node 8.2.1
macOS 10.12.6

**Comment by hellofornow** [comment]
You can use browserType 'exact' and then provide the path to where it's available.
```
await this.session.spawnBrowser('exact', {
                    executablePath: '../path/to/chrome'
                });
```

**Comment by efx** [comment]
@hellofornow, thanks for the tip, that solved it for me. Will add that to the README.md
