### ISSUE TITLE
Web socket to chrome not opened

### ISSUE THREAD

**Issue by bmikkelsen22** [krisselden/chrome-debugging-client#9]
I am trying to take a screenshot of a website using chrome debugging client. 
```typescript
import * as Chrome from 'chrome-debugging-client';
import { DOM, Emulation, Network, Page, Runtime } from 'chrome-debugging-client/dist/protocol/tot';
import * as fs from 'fs';

Chrome.createSession(async (session) => {
    
    const process = await session.spawnBrowser('exact', {
        additionalArguments: ['--headless', '--hide-scrollbars', '--disable-gpu'],
        windowSize: { width: 640, height: 1000 },
        executablePath: '/opt/google/chrome/google-chrome'
    });

    const client = session.createAPIClient('localhost', process.remoteDebuggingPort);

    async function createActiveTab(client: Chrome.IAPIClient) {
        const tab = await client.newTab();
        await client.activateTab(tab.id);
        return tab;
    }
    
    const tab = await createActiveTab(client);
    const debuggerClient = await session.openDebuggingProtocol(tab.webSocketDebuggerUrl);
        
    const page = new Page(debuggerClient);
    const dom = new DOM(debuggerClient);
    const emulation = new Emulation(debuggerClient);
    await page.enable();
    await dom.enable();
    await page.navigate({ url:'https://google.com' });
    setTimeout(async function() {
        const screenshot = await page.captureScreenshot({ });
        const buffer = new Buffer(screenshot.data, 'base64');
        fs.writeFile('google.png', buffer, 'base64', (error) => {
            if (error) {
                console.log(error)
            } else {
                console.log('Screenshot saved.');
            }
        });
    }, 1000);
});
```
But I am getting an issue when taking the screenshot. It looks like either I or the debugging client has not opened the web socket necessary to take the screenshot. Is there anything that I have left out? 

Here's the stack trace: 
```
Error: not opened
    at WebSocket.send (/home/user/Documents/ScreenshotTS/node_modules/ws/lib/WebSocket.js:219:16)
    at Object.send (/home/user/Documents/ScreenshotTS/node_modules/chrome-debugging-client/dist/lib/open-web-socket.js:47:16)
    at Promise (/home/user/Documents/ScreenshotTS/node_modules/chrome-debugging-client/dist/lib/create-debugging-protocol-client.js:18:25)
    at Promise (<anonymous>)
    at DebuggingProtocol.send (/home/user/Documents/ScreenshotTS/node_modules/chrome-debugging-client/dist/lib/create-debugging-protocol-client.js:16:16)
    at Page.captureScreenshot (/home/user/Documents/ScreenshotTS/node_modules/chrome-debugging-client/dist/protocol/tot.js:186:29)
    at Timeout._onTimeout (/home/user/Documents/ScreenshotTS/test.ts:33:39)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
```
Thanks in advance :)

**Comment by hellofornow** [comment]
The issue is your setTimeout doesn't prevent createSession function from ending (which terminates your session -- hence the error you're getting).

You have a couple options:
1) Wrap your timeout in a Promise before taking the screenshot:
```
await new Promise(r => {
    setTimeout(() => r(), 1000);
});
const screenshot = await page.captureScreenshot({ });
const buffer = new Buffer(screenshot.data, 'base64');
fs.writeFile('google.png', buffer, 'base64', (error) => {
    if (error) {
        console.log(error)
    } else {
        console.log('Screenshot saved.');
    }
});
```
fs.writeFile isn't sync so immediately after calling this function the session is lost (which is fine in this scenario).

If you wanted to keep using the session, you could leverage this solution:
```
await new Promise((resolve, reject) => {
    setTimeout(async function () {
        const screenshot = await page.captureScreenshot({});
        const buffer = new Buffer(screenshot.data, 'base64');
        fs.writeFile('google.png', buffer, 'base64', (error) => {
            if (error) {
                console.log(error)
                reject(error);
            } else {
                console.log('Screenshot saved.');
                resolve();
            }
        });
    }, 1000);
}
```
The promise won't be resolved or rejected until the file is written.

**Comment by krisselden** [comment]
you also should wait for the page load event

```js
const pageLoad = new Promise(resolve => {
  page.loadEventFired = (evt) => {
    console.log('loadEventFired', evt);
    resolve();
    page.loadEventFired = null;
  }
});
await page.navigate({ url:'https://google.com' });
await pageLoad;
const screenshot = await page.captureScreenshot({ });
const buffer = new Buffer(screenshot.data, 'base64');
fs.writeFileSync('google.png', buffer);
```
